### PR TITLE
update to bootstrap-select 1.7.4

### PR DESCRIPTION
**Pull request by gmsa**
bootstrap-select updated to 1.7.4

New languages supported:
* da_DK
* ko_KR
* pt_PT
* sk_SK

### CODE REVIEW

**Comment by crevete** [comment]
@gmsa Thanks! But this is not exhaustive. Please add newly supported languages.

**Comment by gmsa** [comment]
done!

**Comment by crevete** [comment]
Where is your commit ?

**Comment by gmsa** [comment]
Sorry, forgot about the commit. It's pushed now.

**Pull request merged**
