### PR TITLE
Added Bootstrap Tags Input to extras

### PR DESCRIPTION
**Pull request by markonikolic**
A new component is added to extras, Bootstrap Tags Input. Original component can be found on the following link:

http://bootstrap-tagsinput.github.io/bootstrap-tagsinput/examples/

### CODE REVIEW

**Comment by crevete** [comment]
@markonikolic First thanks for your contribution. Next time, please create an issue to let us know what and how you want to implement. Also we could collect information from other users to see if there is a real need to do this.

Actually, your PR does not look like a wrapper, but just your customized implementation:
- It is not exhaustive. Why didn't you follow the documentation to  wrap all options, events, etc. It does not support for example multiple select, etc. Please note that if you want to create a simple wrapper for your own usage, you should keep it in your own repository. If you want to share what you do, please do the best you can. Because not only you will use this library and it cost expensive to maintain these libs later.
- It seems that it will not work if you set some options before it's attached to DOM, because all your setters are JSNI methods. Idem for public methods. Please refer slider, summernote, or select wrapper to get an idea.
- Some options should accept multiple forms (string or function) when passing them
- When it is detached from DOM, you have to call ```destroy``` method to clean up event listeners
- As it supports typeahead, maybe we could do something to make it generic with our existing typeahead wrapper. etc.

Too many things to be fixed before merging it.

**Comment by markonikolic** [comment]
@crevete Thanks for your comments. However, I have explicitly asked on the gwtbootstrap group if there is interest in adding such plugin and clearly stressed that it currently supports only functionality we need in our project. The answer from other maintainers was "Sure, just create a new PR", which clearly conflicts with your comments.

https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!topic/gwtbootstrap3/0JjKIyxGhr8

I was waiting for the clear answer before doing any work, but it looks like I wasted my time anyway. The project really should have clear documentation on what is accepted; "How to contribute" is not informative in this sense.

If our wrapper evolves over time and meet the requirements, I will for sure contribute what we have (but will ask again for confirmation from all maintainers before doing any work).

**Comment by markonikolic** [comment]
@crevete Thanks for the recommendations regarding JSNI setters and calling destroy on detach, this will really improve the usability of our wrapper. For sure we will add this to the wrapper and I will transfer changes to mine repo.

I am not sure if I understood comment regarding typeahead, we are already using existing typeahead wrapper (it is enough just to inherit it in .gwt.xml file).

**Comment by sjardine** [comment]
@markonikolic I apologize if I was over zealous in my previous response.  I missed the part regarding only the partial implementation.

**Comment by markonikolic** [comment]
@sjardine @crevete It's ok it happens.

We will need more features on our project for this component and I believe what we need is very close to the expectation you have.

So, I can go with the full implementation, but  can you please confirm if there are interest for this? I don't expect yes/no answer, as I understand that there might be some general issues that prevent component for inclusion. I am more interested if you think that such component would benefit the framework, so I can go with additional work.

The link to the original component is [https://github.com/bootstrap-tagsinput/bootstrap-tagsinput]().

**Comment by crevete** [comment]
@markonikolic Great work, I don't test it yet but the code looks good. Yep, this kind of widget would certainly be welcome. Do you have some additional work to complete the PR?

**Comment by markonikolic** [comment]
@crevete It is not finished yet, several functionalities are missing and it is not properly tested. I'll add features (and test them) according to our priorities, but I believe it will be soon complete. I'm glad such widget is welcomed, I think it is really useful.

**Comment by crevete** [comment]
@markonikolic Thanks again for your contribution :+1:  please let me know when it is finished so that I can merge it.

**Comment by crevete** [comment]
@markonikolic I'll merge this PR so that it is available on snapshot version. Please make new PRs to complete your implementations if necessary. Thanks!

**Comment by markonikolic** [comment]
Ok, thanks. In a few I should finish the remaining TODOs and demo page.

уто, 22. мар 2016. у 11.01 Xiaodong Sun <notifications@github.com> је
написао/ла:

**Pull request merged**
