### PR TITLE
Rename the value set/get methods to allow for HasValue overriding

### PR DESCRIPTION
**Pull request by BenDol**
The new names make more sense anyway.

### CODE REVIEW

**Comment by crevete** [comment]
@BenDol Why not, but please think about people using this widget. I think the better approach is to create new methods doing the same thing (like your commit), and keep get/setValue, then make them reference the newly created methods. So that you can easily override them.

**Comment by BenDol** [comment]
I couldn't do it that way because the method names have to change. They are referencing String but when I extend `Select` and mark my new Select widget with HasValue<T> it clashes with the preexisting setValue/getValue that references `String`. The names have to change or the `Select` widget has to implement HasValue<T>. Either way will require some change management from users.

To be honest this should have been thought about when creating the widget since you always want to keep reserved names for their respective interfaces.

**Comment by sjardine** [comment]
@crevete Do you have anything else to add?

**Comment by crevete** [comment]
@sjardine I pretty want to rewrite the select widget to make it possible to extend it, if I have more time... I currently leave this PR open just for reminder. This is a real issue for me. But currently, I don't think merging it is a good idea. All people using SNAPSHOT version will be impacted...

**Comment by BenDol** [comment]
Are we able to progress this? I am extending the Select widget to use HasValue locally (as suggested) but every time a new snapshot is deployed it overrides my version and I have to recompile to continue working. Snapshot users should expect changes that can break compilation, that is to be expected. Thanks!

**Comment by crevete** [comment]
The select widget is fully re-written (see #275). Now it implements ```HasValue``` method. So I close this PR.

**Pull request closed without merging**
