### PR TITLE
Port Datepicker to Eternicode Datepicker

### PR DESCRIPTION
**Pull request by mdavis95**
~15 languages added, a few removed
No longer an out of range event
Now a clear date event
Merdian, MaxView, and minute step are no longer supported
No time picker in this version

### CODE REVIEW

**Comment by mdavis95** [comment]
#140

**Comment by 0x3333** [comment]
It will break compatibility with fields that need to have the time component in date.

I think it at max, should be implemented side-by-side with current DateTimePicker, and not to replace it.

**Comment by mdavis95** [comment]
Yeah I was thinking I should have renamed the package datepicker instead of datetimepicker and put it side by side.

**Comment by 0x3333** [comment]
Extract the classes, revert your changes and add the classes back. I think it should work.

**Comment by mdavis95** [comment]
Ok I have done that and updated the demo as well
https://github.com/gwtbootstrap3/gwtbootstrap3-demo/pull/78

**Comment by jgodi** [comment]
I will try to look at this tomorrow or tonight. Thanks!

**Comment by jgodi** [comment]
LGTM, thanks for the work!

**Comment by Unimax** [comment]
anyone working on complete datetimepicker (i mean the timepicker part?).

**Comment by jgodi** [comment]
There is a DateTimePicker currently in the extras, but it is a bit out of date and the underlying JS library doesn't have much traction anymore. It would be nice if someone can upgrade this!

**Comment by Unimax** [comment]
@jgodi new to github i have a working model for the http://eonasdan.github.io/bootstrap-datetimepicker/ with some less working options for now will be finishing all must have options at least. is there a way to chat here? i think i committed before complete changes :( will be figuring out how to edit it.

**Pull request merged**
