### PR TITLE
Add Validation to the Select Widget

### PR DESCRIPTION
**Pull request by BenDol**
The ChangeHandler will invoke as the blur event

### CODE REVIEW

**Comment by BenDol** [comment]
This change also has setValidationEnabled/isValidationEnabled to sync this patch https://github.com/gwtbootstrap3/gwtbootstrap3/pull/405

**Comment by sjardine** [comment]
Checks have failed. Can you please fix?

**Comment by BenDol** [comment]
They contain setValidationEnabled/isValidationEnabled which is in the patch on the main repository. Do you want me to remove them in this patch? They won't fail once that PR is accepted is all.

**Comment by sjardine** [comment]
Would you mind reviewing #164 and providing me with feedback? @crevete What is your opinion?

**Comment by BenDol** [comment]
Just FYI I made `Select` widget `HasValue<String>` to give compatibility with some abstractions I use.

**Comment by BenDol** [comment]
Having validation on the Select widget is important in the use case with Multiselect enabled, you have the option not to select anything and in many cases mandatory selections are required. That was what I needed it for anyway.

**Comment by crevete** [comment]
@BenDol @sjardine 
First, as I said in #164, wrappers in extra project should be as simple as possible. Maybe you are right on the use case with multiple select enabled, but it's not good approach to put the "second" layer on a wrapper widget. Anyway, if you really need it, you are free to extend it by adding validation support.
Second, make this select implement ```HasValue<String>``` is not correct. On multiple selection, the value of the select should be a ```List<String>```. Ideally, the select should be typed with an generic template and provides 2 implementations : one with ```String```, and another with ```List<String>```.

So I'm sorry, this PR could not be merged. One more time, if you really need implement like this, fell free to extend select.

**Comment by BenDol** [comment]
Its not possible for me to extend Select since it has methods that clash with HasValue i.e. getValue/setValue so It throws errors. In order to get the validation working with the default validator mixins the widget needs to implement HasValue, seems strange not to support validation in these widgets.

**Comment by crevete** [comment]
@BenDol I don't see why you cannot extend Select... Sure, methods like getValue/setValue do already exist in Select, but why you cannot override it ?

```
@Override
public String getValue() {
  return "myvalue for validation";
}

// If you want keep the original getValue method, just rename it:
public String getSelectValue() {
  return return super.getValue();
}
```

Why do not support validation stuff, I have sais before, it is not the wrapper's job. The wrapper should only do what the native JS library does.

**Comment by crevete** [comment]
Select should implement ```HasValue<T>```, you are right. But the type should be generic, not ONLY ```HasValue<String>```.

**Comment by BenDol** [comment]
But then shouldn't you be removing all these non-wrapper related mixins then?
```java
private final AttributeMixin<Select> attributeMixin = new AttributeMixin<Select>(this);
private final FocusableMixin<Select> focusableMixin = new FocusableMixin<Select>(this);
private final EnabledMixin<Select> enabledMixin = new EnabledMixin<Select>(this);
```

**Comment by sjardine** [comment]
@BenDol I agree with the Select issue regarding HasValue<String>.  If select returns multiple values.  It really doesn't give a good representation of the value to be returned from Select.

@crevete  I don't think I agree with your opinion that wrappers should *ONLY* be simple wrappers.  We include many convience methods as mentioned above by @BenDol.  I am not sure it was the intention of @jgodi or @svenjacobs to only provide the functionality of the native JS library but it doesn't really matter.  I *DO* know that there are many of us that want these extra form components to work with the gwt editor framework and simple wrappers won't do that.

I think I will agree that we can have a simple wrapper class and then an extended class with whatever extra gwt stuff we think is necessary.  We could include ExtSelect in the same package or have an ext package and then the extended Select element.  Do you have an opinion regarding the naming convention?

**Comment by BenDol** [comment]
Probably SelectXxx is better to stick with the select prefix. What about differentiating them by ext package? Then leave the name Select. An idea perhaps.

**Comment by crevete** [comment]
@sjardine @BenDol what I mean simple wrapper is not ONLY wrapper off course. I totally agree with you on extra widgets should work with editor framework, so that's why I said Select should implement ```HasValue```. Please do not miss understand me :-) But the validation stuff is different than supporting editor framework. It's a second layer on wrapper widgets. Beware some extra widgets (native JS lib) do their own validation stuff too, in this case, it may cause problems with our validation system. Beside, the fact that we "hard-coded" the validation implementation (i.e.: position/color of error message) in the library may not be convenient for end-users (If the user uses an another bootstrap theme, the hard-coded error message color may be incompatible, etc.). Also, it costs expensive, especially when updating to a new version of the native JS lib that includes more significant changes. That's why I think, our extra lib should be compatible with editor framework for validation stuff, but it's implement would better to be implemented by users.

**Comment by sjardine** [comment]
@crevete  If you have suggestions on removing "hard-coded" elements in the validation implementation please let me know.  I would welcome any suggestions on how to implement validation in a more theme independent way. :)

I think its a mistake to just tell users that they have to implement their own validation for components in the extras package.  Any extra component that uses a subclass of ValueBoxBase for its input element already has the validation implementation included.  We are just preventing our users from accessing the functionality.

I would suggest we discuss the changes we would like to see in the client side validation implementation as well as how we could provide validation to our users so this issue doesn't keep coming up over and over.

**Pull request closed without merging**
