### PR TITLE
TagsInput update

### PR DESCRIPTION
**Pull request by markonikolic**
Added almost all features of original component. Major changes:

- handling of all events
- support for single and multiple values tags input (based on `<input>` or `<select>` tag)
- finished support for JS and Java objects as taginput items
- bug fixes

### CODE REVIEW

**Comment by crevete** [comment]
Could you please merge your branch master ? Thanks

**Comment by markonikolic** [comment]
Merged. Please let me know if something more is needed.

**Comment by crevete** [comment]
Ok I'll check it later. Could you please update also the demo page?

**Comment by markonikolic** [comment]
Yes, i have planned to update demo page, but I am not sure if I will be
able to do it next week, probably week after.

Is there some documentation regarding usage, or it is demo page?

Regards,
Marko

суб, 2. апр 2016. 09.41 Xiaodong Sun <notifications@github.com> је
написао/ла:

**Comment by crevete** [comment]
Just the demo page: http://gwtbootstrap3.github.io/gwtbootstrap3-demo/snapshot/#tagsInput

Thanks

**Pull request merged**
