### PR TITLE
FullCalendar 2.3.1

### PR DESCRIPTION
**Pull request by koljascasino**
Updated to FullCalendar 2.3.1, see #121  

The default of the properties `selectable` and `selectHelper` has changed to align with the original javascript library and its documentation. If you want to be able to select empty cells in your calendar, you will now need to set this explicitly:
```java
CalendarConfig config = new CalendarConfig();
config.setSelectable(true);
config.setSelectHelper(true);
``` 

The .css has been updated as well from the original library file so this might overwrite changes made in 390e27846a8a9aee5303b59b3c2fe4a62bbdaef9. @bauna can you fix this again or get it into the original projects http://fullcalendar.io/wiki/Contributing/ ?

### CODE REVIEW

**Comment by koljascasino** [comment]
[ERROR] error reading /home/travis/.m2/repository/com/google/gwt/gwt-user/2.7.0/gwt-user-2.7.0.jar; error in opening zip file

@jgodi cannot see what is wrong here, can you help?

**Comment by jgodi** [comment]
Ill merge this, if it fails then we can fix it once it's merged. Shouldn't fail. Thanks!

**Comment by jgodi** [comment]
Ya, build successfully once merged. Thanks!

**Comment by koljascasino** [comment]
Great, thanks!

**Pull request merged**
